services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: gestion_stock
    ports:
      - "${MYSQL_PORT:-3307}:3306"
    volumes:
      - db_data_dev:/var/lib/mysql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    command: sh -c "./scripts/wait-for-it.sh db:3306 -- npx prisma migrate dev && npm run dev"
    env_file:
      - .env.dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "100"
      TSC_WATCHFILE: UseFsEventsWithFallbackDynamicPolling
    volumes:
      - ./server:/app
    depends_on:
      - db
    ports:
      - "${SERVER_PORT:-4000}:4000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    command: sh -c "npm run dev -- --hostname 0.0.0.0 --port 3000 --webpack"
    env_file:
      - .env.dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "100"
      WATCHPACK_POLLING: "true"
      WATCHPACK_POLL_INTERVAL: "100"
      NEXT_WEBPACK_USEPOLLING: "true"
      NEXT_DISABLE_TURBOPACK: "1"
      TSC_WATCHFILE: UseFsEventsWithFallbackDynamicPolling
      TAILWIND_MODE: watch
    volumes:
      - ./client:/app
    depends_on:
      - server
    ports:
      - "${CLIENT_PORT:-3000}:3000"

volumes:
  db_data_dev:
